### ISSUE TITLE
ModelValueResolver resolves for optional parameters

### ISSUE THREAD

**Issue by RobinHoutevelts** [wieni/wmmodel#24]
## Description

The ModelValueResolver resolves for optional parameters.

### Steps to reproduce

Assume we have a route to move the relation between tags.

```yml
foo.mark_tag_as_root:
    path: /move/{tag}
    options:
        parameters:
            tag: {type: 'entity:taxonomy_term'}

foo.mark_tag_as_child:
    path: /move/{tag}/{parentTag}
    options:
        parameters:
            tag: {type: 'entity:taxonomy_term'}
            parentTag: {type: 'entity:taxonomy_term'}
```

And this controller method:

```php
public function move(Tag $tag, ?Tag $parentTag = null): void
{
    if (!$parentTag) {
        // Mark $tag as root
    } else {
        // Mark $tag as child of $parentTag
    }
}
```

### Expected result

When I visit `/move/123`, I expect:

- My Controller method to be called
- `$tag` to be a Term with id 123
- `$parentTag` to be `null`.

### Actual result

`$parentTag` is the same as `$tag` instead of `null`
